export const searchData = [
  // --- PROJELER ---
  {
    id: 1,
    title: 'The Modular Home',
    category: 'Art',
    year: '2026',
    type: 'project',
    href: '/works/the-modular-home',
    image: '/images/projects/the-modular-home.jpg',
    keywords: ['modular', 'home', 'art', 'architecture'],
  },
  {
    id: 2,
    title: 'Riva 937',
    category: 'Art',
    year: '2024',
    type: 'project',
    href: '/works/riva-937',
    image: '/images/projects/riva-937.png',
    keywords: ['riva', 'boat', 'art'],
  },
  {
    id: 3,
    title: 'Desilight',
    category: 'Design',
    year: '2025',
    type: 'project',
    href: '/works/desilight',
    image: '/images/projects/desilight-2025.png',
    keywords: ['light', 'design', 'lamp'],
  },
  {
    id: 4,
    title: 'Viberon',
    category: 'Design',
    type: 'project',
    href: '/works/viberon',
    image: '/images/projects/viberon-2025.png',
    keywords: ['viberon', 'design'],
  },
  {
    id: 5,
    title: 'Fuantei',
    category: 'Design',
    type: 'project',
    href: '/works/fuantei',
    image: '/images/projects/fuantei.jpg',
    keywords: ['fuantei', 'design'],
  },
  {
    id: 6,
    title: 'Colosseum Name',
    category: 'Graphic',
    type: 'project',
    href: '/works/colosseum-name',
    image: '/images/projects/colosseum-name.png',
    keywords: ['colosseum', 'graphic', 'typography'],
  },
  {
    id: 7,
    title: 'Extreamity',
    category: 'Art',
    type: 'project',
    href: '/works/extreamity',
    image: '/images/projects/extreamity.png',
    keywords: ['extreamity', 'art'],
  },

  // --- SAYFALAR ---
  {
    id: 8,
    title: 'Doruk Bicer — About',
    category: 'Page',
    type: 'page',
    href: '/doruk-bicer',
    image: '/images/doruk-bicer.jpg',
    keywords: ['about', 'doruk', 'bicer', 'designer', 'istanbul'],
  },
  {
    id: 9,
    title: 'Studio',
    category: 'Page',
    type: 'page',
    href: '/studio',
    image: null,
    keywords: ['studio', 'workspace'],
  },
  {
    id: 10,
    title: 'Contact',
    category: 'Page',
    type: 'page',
    href: '/contact',
    image: null,
    keywords: ['contact', 'email', 'iletişim'],
  },
];
