import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const formaDJRDisplay = localFont({
  src: [
    { path: "../fonts/FormaDJRDisplay-Thin.woff2", weight: "100", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-Light.woff2", weight: "300", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-Regular.woff2", weight: "400", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-Medium.woff2", weight: "500", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-Bold.woff2", weight: "700", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../fonts/FormaDJRDisplay-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-forma-djr-display",
});

const helveticaNeue = localFont({
  src: [
    { path: "../fonts/HelveticaNeueLight.woff2", weight: "300", style: "normal" },
    { path: "../fonts/HelveticaNeueBold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-helvetica-neue",
});

const minionPro = localFont({
  src: [{ path: "../fonts/MinionPro-Regular.woff2", weight: "400", style: "normal" }],
  variable: "--font-minion-pro",
});

export default function RootLayout({ children }) {
  return (
    <html lang={"en"}>
      <body
        className={`${helveticaNeue.variable} ${minionPro.variable} ${formaDJRDisplay.variable} font-forma-djr-display antialiased w-full overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
