import "../globals.css";
import localFont from 'next/font/local';
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Header from "@/components/header";
import Footer from "@/components/footer";
import SideBar from "@/components/sidebar";
import MainContent from "@/components/mainContent";

const formaDJRDisplay = localFont({
  src: [
    { path: '../../fonts/FormaDJRDisplay-Thin.woff2', weight: '100', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-ExtraLight.woff2', weight: '200', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-Light.woff2', weight: '300', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-Bold.woff2', weight: '700', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-ExtraBold.woff2', weight: '800', style: 'normal' },
    { path: '../../fonts/FormaDJRDisplay-Black.woff2', weight: '900', style: 'normal' },
  ],
  variable: '--font-forma-djr-display'
});

const helveticaNeue = localFont({
  src: [
    { path: '../../fonts/HelveticaNeueLight.woff2', weight: '300', style: 'normal' },
  ],
  variable: '--font-helvetica-neue',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={`${helveticaNeue.variable} ${formaDJRDisplay.variable} font-forma-djr-display antialiased w-full flex`}>
        <NextIntlClientProvider>
          <MainContent>
            <Header />
            {children}
            <Footer />
          </MainContent>
          <SideBar />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
