import Header from '@/components/header';
import Footer from '@/components/footer';
import SideBar from '@/components/sidebar';
import { ScrollToTop } from '@/components/scrollToTop';

export const metadata = { title: 'Create Next App', description: 'Generated by create next app' };

export default function SiteLayout({ children }) {
  return (
    <>
      <ScrollToTop />
      <main className="w-full min-h-screen gridContainer overflow-x-hidden">
        <Header />
        {children}
        <Footer />
      </main>
      <SideBar />
    </>
  );
}
